-- 영화 상영 회차 테이블
CREATE TABLE T_MOVIE_SHOWTIME (
    SHOWTIME_ID NUMBER PRIMARY KEY,
    MOVIE_ID NUMBER NOT NULL,
    THEATER_ID NUMBER NOT NULL,
    SCREEN_ID NUMBER NOT NULL,
    START_AT DATE NOT NULL,
    END_AT DATE NOT NULL,
    SEAT_COUNT NUMBER NOT NULL,
    CONSTRAINT FK_SHOWTIME_MOVIE FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(MOVIE_ID),
    CONSTRAINT FK_SHOWTIME_THEATER FOREIGN KEY (THEATER_ID) REFERENCES T_THEATER(THEATER_ID),
    CONSTRAINT FK_SHOWTIME_SCREEN FOREIGN KEY (SCREEN_ID) REFERENCES T_SCREEN(SCREEN_ID),
    CONSTRAINT CK_SHOWTIME_PERIOD CHECK (END_AT > START_AT),
    CONSTRAINT CK_SHOWTIME_SEAT_COUNT CHECK (SEAT_COUNT > 0)
);

CREATE SEQUENCE MOVIE_SHOWTIME_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 상영 회차별 좌석 테이블
-- BOOKER_USER_UID가 NULL이면 아직 예매되지 않은 좌석입니다.
CREATE TABLE T_MOVIE_SHOWTIME_SEAT (
    SHOWTIME_ID NUMBER NOT NULL,
    SEAT_NO VARCHAR2(10) NOT NULL,
    BOOKER_USER_UID NUMBER,
    CONSTRAINT PK_SHOWTIME_SEAT PRIMARY KEY (SHOWTIME_ID, SEAT_NO),
    CONSTRAINT FK_SHOWTIME_SEAT_SHOWTIME FOREIGN KEY (SHOWTIME_ID) REFERENCES T_MOVIE_SHOWTIME(SHOWTIME_ID),
    CONSTRAINT FK_SHOWTIME_SEAT_USER FOREIGN KEY (BOOKER_USER_UID) REFERENCES USERS(USER_UID)
);
