-- 상영관별 논리 그리드 크기
ALTER TABLE T_SCREEN ADD (
    GRID_COLUMNS NUMBER DEFAULT 20 NOT NULL,
    GRID_ROWS NUMBER DEFAULT 16 NOT NULL,
    CONSTRAINT CK_SCREEN_GRID_COLUMNS CHECK (GRID_COLUMNS > 0),
    CONSTRAINT CK_SCREEN_GRID_ROWS CHECK (GRID_ROWS > 0)
);

CREATE TABLE T_SCREEN_SEAT (
    SCREEN_SEAT_ID NUMBER PRIMARY KEY,
    SCREEN_ID NUMBER NOT NULL,
    SEAT_NO VARCHAR2(10) NOT NULL,
    GRID_X NUMBER NOT NULL,
    GRID_Y NUMBER NOT NULL,
    SEAT_TYPE VARCHAR2(50),
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT FK_SCREEN_SEAT_SCREEN FOREIGN KEY (SCREEN_ID) REFERENCES T_SCREEN(SCREEN_ID),
    CONSTRAINT UK_SCREEN_SEAT_NO UNIQUE (SCREEN_ID, SEAT_NO),
    CONSTRAINT UK_SCREEN_SEAT_POSITION UNIQUE (SCREEN_ID, GRID_X, GRID_Y)
);

CREATE SEQUENCE SCREEN_SEAT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE T_SCREEN_LAYOUT_OBJECT (
    LAYOUT_OBJECT_ID NUMBER PRIMARY KEY,
    SCREEN_ID NUMBER NOT NULL,
    OBJECT_TYPE VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(50),
    GRID_X NUMBER NOT NULL,
    GRID_Y NUMBER NOT NULL,
    GRID_WIDTH NUMBER DEFAULT 1 NOT NULL,
    GRID_HEIGHT NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT FK_LAYOUT_OBJECT_SCREEN FOREIGN KEY (SCREEN_ID) REFERENCES T_SCREEN(SCREEN_ID),
    CONSTRAINT UK_LAYOUT_OBJECT_NAME UNIQUE (SCREEN_ID, OBJECT_TYPE, NAME)
);

CREATE SEQUENCE SCREEN_LAYOUT_OBJECT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 상영 회차가 생성될 때 상영관 좌석 배치를 스냅샷으로 복사합니다.
ALTER TABLE T_MOVIE_SHOWTIME_SEAT ADD (
    SCREEN_SEAT_ID NUMBER,
    GRID_X NUMBER,
    GRID_Y NUMBER,
    SEAT_TYPE VARCHAR2(50),
    CONSTRAINT FK_SHOWTIME_SEAT_SCREEN_SEAT FOREIGN KEY (SCREEN_SEAT_ID) REFERENCES T_SCREEN_SEAT(SCREEN_SEAT_ID)
);
