CREATE TABLE T_SCREEN (
    SCREEN_ID NUMBER PRIMARY KEY,
    THEATER_ID NUMBER NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    CAPACITY NUMBER NOT NULL,
    CONTEXT VARCHAR2(1000),
    SCREENX_YN CHAR(1) DEFAULT 'N' NOT NULL,
    TWO_D_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    THREE_D_YN CHAR(1) DEFAULT 'N' NOT NULL,
    FOUR_D_YN CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT FK_SCREEN_THEATER FOREIGN KEY (THEATER_ID) REFERENCES T_THEATER(THEATER_ID),
    CONSTRAINT CK_SCREEN_CAPACITY CHECK (CAPACITY > 0),
    CONSTRAINT CK_SCREEN_SCREENX CHECK (SCREENX_YN IN ('Y', 'N')),
    CONSTRAINT CK_SCREEN_2D CHECK (TWO_D_YN IN ('Y', 'N')),
    CONSTRAINT CK_SCREEN_3D CHECK (THREE_D_YN IN ('Y', 'N')),
    CONSTRAINT CK_SCREEN_4D CHECK (FOUR_D_YN IN ('Y', 'N'))
);

CREATE SEQUENCE SCREEN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
