-- 기존 영화관 테이블과 시퀀스를 삭제한 뒤 다시 생성합니다.
DROP TABLE T_THEATER CASCADE CONSTRAINTS;
DROP SEQUENCE THEATER_SEQ;

-- LOCATION_CODE만 T_CODE의 GROUP_CODE = 'LOCATION' 코드값을 사용합니다.
CREATE TABLE T_THEATER (
    THEATER_ID NUMBER PRIMARY KEY,
    THEATER_NAME VARCHAR2(50) NOT NULL,
    LOCATION_CODE VARCHAR2(50) NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CONTEXT VARCHAR2(1000),
    CONSTRAINT CK_THEATER_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE SEQUENCE THEATER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- LOCATION_CODE 값은 T_CODE의 LOCATION 그룹 CODE 값에 맞춰 사용하세요.
INSERT INTO T_THEATER (THEATER_ID, THEATER_NAME, LOCATION_CODE, USE_YN, CONTEXT)
VALUES (THEATER_SEQ.NEXTVAL, 'CGV 강남', 'SEOUL', 'Y', '강남역 인근 영화관');

INSERT INTO T_THEATER (THEATER_ID, THEATER_NAME, LOCATION_CODE, USE_YN, CONTEXT)
VALUES (THEATER_SEQ.NEXTVAL, 'CGV 해운대', 'BUSAN', 'Y', '해운대 해변 인근 영화관');
